name: Build Python Package

on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]
    paths:
      - "pyproject.toml"
      - "setup.cfg"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "pyproject.toml"
      - "setup.cfg"
      - ".github/workflows/build.yml"

permissions:
  contents: read

jobs:
  deploy:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m Build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == "tags"
        with:
          name: ${{github.ref_name}}
          path: dist
